<?php

declare(strict_types=1);

use Scandiweb\WordPressIntegration\Block\Widget\WordPressPost;

/** @var WordPressPost $block */

$layout = $block->getData('layout');
$post = $block->getPost();
$videoUrl = $post->getVideoUrl();
$videoEmbed = $post->getVideoEmbed();
$categoryLabel = $post->getCategoryLabel();
$categoryUrl = $post->getCategoryUrl();
$date = $post->getDateGmt();
$showVideo = !empty($videoUrl) || !empty($videoEmbed);
$videoIsVideo = strpos((string)$videoEmbed, '<video') !== false;
$videoIsIframe = strpos((string)$videoEmbed, '<iframe') !== false;
$showCategory = !empty($categoryUrl) && $layout === 'vertical';
$linkTarget = $block->getData('link_target');
?>

<style>
    .WordPressPost-horizontal {
        display: flex;
        flex-direction: row;
    }

    .WordPressPost_VideoWrap {
        aspect-ratio: 16 / 9;
        flex: 2;
        display: flex;
        position: relative;
    }

    .WordPressPost video,
    .WordPressPost iframe,
    .WordPressPost .WordPressPost_Video,
    .WordPressPost .WordPressPost_Image {
        width: 100%;
        height: 100%;
    }

    .WordPressPost_Image {
        aspect-ratio: 16 / 9;
        object-fit: cover;
    }

    .WordPressPost_Play {
        position: absolute;
        width: 100%;
        height: 100%;
        display: grid;
        place-items: center;
    }

    .WordPressPost_Play a {
        width: 68px;
        height: 48px;
        padding: 0 0 0 3px;
    }

    /* YouTube button */
    .WordPressPost_Play a svg path:first-of-type {
        opacity: 0.8;
        fill: #212121;
    }
    .WordPressPost_Play a:hover svg path:first-of-type {
        opacity: 1;
        fill: #f00;
    }

    .WordPressPost_PostDetails {
        flex: 1;
        padding: 0 16px 48px 16px;
        position: relative;
    }

    .WordPressPost_TopInfo {
        padding-top: 16px;
    }

    .WordPressPost_Category {
        padding: 8px;
        background: #F5F5F5;
        color: #000;
        font-weight: bold;
    }

    .WordPressPost_Date {
        display: inline-block;
        margin-right: 32px;
    }

    .WordPressPost_Link {
        position: absolute;
        bottom: 16px;
    }

    .WordPressPost_Image-hidden,
    .WordPressPost_Video-hidden {
        display: none;
    }
</style>

<?php if ($showVideo): ?>
    <script>
        function playWordPressPostVideo<?= $post->getPostId() ?>() {
            const postId = <?= $post->getPostId() ?>;
            const image = document.getElementById('image-' + postId);
            const play = document.getElementById('play-' + postId);
            const video = document.getElementById('video-' + postId);

            image.remove();
            play.remove();
            video.classList.remove('WordPressPost_Video-hidden');
            video.play();
            return false;
        }
    </script>
<?php endif; ?>

<article class="WordPressPost WordPressPost-<?= $layout ?>">
    <?php if (!$showVideo): ?>
        <img id="image-<?= $post->getPostId() ?>"
             class="WordPressPost_Image"
             src="<?= $post->getImageUrl() ?>"
             loading="lazy"
             alt="<?= $post->getTitle() ?>"
        />
    <?php endif; ?>
    <?php if ($videoIsIframe): ?>
        <div class="WordPressPost_VideoWrap">
            <?= $videoEmbed ?>
        </div>
    <?php elseif ($videoIsVideo): ?>
        <div class="WordPressPost_VideoWrap">
            <img id="image-<?= $post->getPostId() ?>"
                 class="WordPressPost_Image"
                 src="<?= $post->getImageUrl() ?>"
                 loading="lazy"
                 alt="<?= $post->getTitle() ?>"
            />
            <div id="play-<?= $post->getPostId() ?>" class="WordPressPost_Play">
                <a onClick="playWordPressPostVideo<?= $post->getPostId() ?>()" href="javascript:;">
                    <!-- YouTube play button -->
                    <svg height="100%" version="1.1" viewBox="0 0 68 48" width="100%"><path class="ytp-large-play-button-bg" d="M66.52,7.74c-0.78-2.93-2.49-5.41-5.42-6.19C55.79,.13,34,0,34,0S12.21,.13,6.9,1.55 C3.97,2.33,2.27,4.81,1.48,7.74C0.06,13.05,0,24,0,24s0.06,10.95,1.48,16.26c0.78,2.93,2.49,5.41,5.42,6.19 C12.21,47.87,34,48,34,48s21.79-0.13,27.1-1.55c2.93-0.78,4.64-3.26,5.42-6.19C67.94,34.95,68,24,68,24S67.94,13.05,66.52,7.74z" fill="#f00"></path><path d="M 45,24 27,14 27,34" fill="#fff"></path></svg>
                </a>
            </div>
            <?= str_replace(
                '<video',
                '<video class="WordPressPost_Video WordPressPost_Video-hidden"',
                $videoEmbed)
            ?>
        </div>
    <?php elseif (!empty($videoUrl)): ?>
        <div class="WordPressPost_VideoWrap">
            <img id="image-<?= $post->getPostId() ?>"
                 class="WordPressPost_Image"
                 src="<?= $post->getImageUrl() ?>"
                 loading="lazy"
                 alt="<?= $post->getTitle() ?>"
            />
            <div id="play-<?= $post->getPostId() ?>" class="WordPressPost_Play">
                <a onClick="playWordPressPostVideo<?= $post->getPostId() ?>()" href="javascript:;">
                    <!-- YouTube play button -->
                    <svg height="100%" version="1.1" viewBox="0 0 68 48" width="100%"><path class="ytp-large-play-button-bg" d="M66.52,7.74c-0.78-2.93-2.49-5.41-5.42-6.19C55.79,.13,34,0,34,0S12.21,.13,6.9,1.55 C3.97,2.33,2.27,4.81,1.48,7.74C0.06,13.05,0,24,0,24s0.06,10.95,1.48,16.26c0.78,2.93,2.49,5.41,5.42,6.19 C12.21,47.87,34,48,34,48s21.79-0.13,27.1-1.55c2.93-0.78,4.64-3.26,5.42-6.19C67.94,34.95,68,24,68,24S67.94,13.05,66.52,7.74z" fill="#f00"></path><path d="M 45,24 27,14 27,34" fill="#fff"></path></svg>
                </a>
            </div>
            <video controls
                   id="video-<?= $post->getPostId() ?>"
                   class="WordPressPost_Video WordPressPost_Video-hidden"
            >
                <source src="<?= $videoUrl ?>" />
            </video>
        </div>
    <?php endif; ?>

    <div class="WordPressPost_PostDetails">
        <?php if ($showCategory): ?>
            <div class="WordPressPost_TopInfo">
                <div class="WordPressPost_Date"><?= $block->formatPostDate($date) ?></div>
                <span>
                    <a class="WordPressPost_Category" target="<?= $linkTarget ?>" href="<?= $categoryUrl ?>">
                        #<?= $categoryLabel ?>
                    </a>
                </span>
            </div>
        <?php endif; ?>
        <h3><?= $post->getTitle() ?></h3>
        <p><?= $post->getExcerpt() ?></p>
        <?php if (!empty($post->getExcerpt())): ?>
            <a class="WordPressPost_Link" target="<?= $linkTarget ?>" href="<?= $post->getLink() ?>"><?= __('Read More') ?></a>
        <?php endif; ?>
    </div>
</article>
